<?php

namespace Tests\Support;

/**
 * Manifest machine-readable canônico das 65 capacidades (QA / Contrato).
 * Fonte única de verdade para testes de contrato, descobribilidade e cobertura.
 */
class CapabilityCatalog
{
    /**
     * Retorna todas as 65 capacidades catalogadas.
     *
     * @return array<string, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            // Dominio 1: Identidade e Acesso (CAP-ID-001..011)
            'CAP-ID-001' => [
                'id' => 'CAP-ID-001',
                'nome' => 'Autenticacao / Login',
                'dominio' => 'identidade',
                'papel_minimo' => 'visitante',
                'tipo' => 'PAGE',
                'rota_v1' => 'login',
                'rota_v2' => 'login',
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-002' => [
                'id' => 'CAP-ID-002',
                'nome' => 'Logout',
                'dominio' => 'identidade',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => 'logout',
                'rota_v2' => 'logout',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-003' => [
                'id' => 'CAP-ID-003',
                'nome' => 'Alterar propria senha',
                'dominio' => 'identidade',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => 'identidade.perfil.senha.update',
                'rota_v2' => 'v2.identidade.perfil.senha.update',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-SEC-001
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-004' => [
                'id' => 'CAP-ID-004',
                'nome' => 'Listar usuarios',
                'dominio' => 'identidade',
                'papel_minimo' => 'supervisor',
                'tipo' => 'LIST',
                'rota_v1' => 'v1.identidade.usuarios.index',
                'rota_v2' => 'v2.identidade.usuarios.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-005' => [
                'id' => 'CAP-ID-005',
                'nome' => 'Criar novo usuario (admin)',
                'dominio' => 'identidade',
                'papel_minimo' => 'supervisor',
                'tipo' => 'CREATE',
                'rota_v1' => 'v1.identidade.usuarios.create',
                'rota_v2' => 'v2.identidade.usuarios.create',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-USR-007/009
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-006' => [
                'id' => 'CAP-ID-006',
                'nome' => 'Resetar senha por operador',
                'dominio' => 'identidade',
                'papel_minimo' => 'supervisor',
                'tipo' => 'ACTION',
                'rota_v1' => 'identidade.usuarios.resetar-senha',
                'rota_v2' => 'v2.identidade.usuarios.resetar-senha',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-007' => [
                'id' => 'CAP-ID-007',
                'nome' => 'Mudar permissao de usuario',
                'dominio' => 'identidade',
                'papel_minimo' => 'supervisor',
                'tipo' => 'UPDATE',
                'rota_v1' => 'identidade.usuarios.atualizar-papel',
                'rota_v2' => 'v2.identidade.usuarios.atualizar-papel',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-008' => [
                'id' => 'CAP-ID-008',
                'nome' => 'Exclusao/desativacao de usuario',
                'dominio' => 'identidade',
                'papel_minimo' => 'superadministrador',
                'tipo' => 'DELETE/DESATIVAR',
                'rota_v1' => 'v1.identidade.usuarios.destroy',
                'rota_v2' => 'v2.identidade.usuarios.destroy',
                'requires_navigation' => false,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'T3-14',
            ],
            'CAP-ID-009' => [
                'id' => 'CAP-ID-009',
                'nome' => 'Alternar tema / preferencia',
                'dominio' => 'identidade',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => 'tema.alternar',
                'rota_v2' => 'tema.alternar',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-010' => [
                'id' => 'CAP-ID-010',
                'nome' => 'Salvar anotacoes do operador',
                'dominio' => 'identidade',
                'papel_minimo' => 'operador',
                'tipo' => 'UPDATE',
                'rota_v1' => 'identidade.perfil.anotacao.update',
                'rota_v2' => 'v2.identidade.anotacoes.update',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-NOTE-001
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-ID-011' => [
                'id' => 'CAP-ID-011',
                'nome' => 'Autocadastro com convite/segredo',
                'dominio' => 'identidade',
                'papel_minimo' => 'visitante',
                'tipo' => 'ACTION',
                'rota_v1' => null,
                'rota_v2' => null,
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido', // Codigo Morto / Nao Promover
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'EVO-SAAS-001',
            ],

            // Dominio 2: Gestao de Ciclo de Vida do RMA (CAP-RMA-001..024)
            'CAP-RMA-001' => [
                'id' => 'CAP-RMA-001',
                'nome' => 'Criar novo RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'CREATE',
                'rota_v1' => 'v1.rmas.create',
                'rota_v2' => 'v2.rmas.create',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-002' => [
                'id' => 'CAP-RMA-002',
                'nome' => 'Buscar / Localizar RMAs',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'FILTER',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-003' => [
                'id' => 'CAP-RMA-003',
                'nome' => 'Fila de Entrada',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'LIST',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-004' => [
                'id' => 'CAP-RMA-004',
                'nome' => 'Fila dedicada de Recebidos',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'LIST',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-005' => [
                'id' => 'CAP-RMA-005',
                'nome' => 'Fila de Encaminhados',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'LIST',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-006' => [
                'id' => 'CAP-RMA-006',
                'nome' => 'Fila de Concluidos',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'LIST',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-007' => [
                'id' => 'CAP-RMA-007',
                'nome' => 'Fila de Aguardando Credito',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'LIST',
                'rota_v1' => 'rmas.credito.index',
                'rota_v2' => 'rmas.credito.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-008' => [
                'id' => 'CAP-RMA-008',
                'nome' => 'Fila de Arquivados',
                'dominio' => 'rma',
                'papel_minimo' => 'supervisor',
                'tipo' => 'LIST',
                'rota_v1' => 'rmas.controle.index',
                'rota_v2' => 'v2.identidade.controle.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-009' => [
                'id' => 'CAP-RMA-009',
                'nome' => 'Rota Retornou (0 bytes)',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => null,
                'rota_v2' => null,
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido', // Codigo Morto
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'N/A',
            ],
            'CAP-RMA-010' => [
                'id' => 'CAP-RMA-010',
                'nome' => 'Detalhe e Edicao de RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'DETAIL',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-011' => [
                'id' => 'CAP-RMA-011',
                'nome' => 'Transicao: Receber RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'WORKFLOW',
                'rota_v1' => 'v1.rmas.transicao.receber',
                'rota_v2' => 'v2.rmas.transicao.receber',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-012' => [
                'id' => 'CAP-RMA-012',
                'nome' => 'Transicao: Encaminhar RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'WORKFLOW',
                'rota_v1' => 'v1.rmas.transicao.encaminhar',
                'rota_v2' => 'v2.rmas.transicao.encaminhar',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-013' => [
                'id' => 'CAP-RMA-013',
                'nome' => 'Transicao: Concluir RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'WORKFLOW',
                'rota_v1' => 'v1.rmas.transicao.concluir',
                'rota_v2' => 'v2.rmas.transicao.concluir',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-014' => [
                'id' => 'CAP-RMA-014',
                'nome' => 'Transicao: Reverter p/ Entrada',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'WORKFLOW',
                'rota_v1' => 'v1.rmas.transicao.reverter',
                'rota_v2' => 'v2.rmas.transicao.reverter',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-015' => [
                'id' => 'CAP-RMA-015',
                'nome' => 'Arquivar RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'supervisor',
                'tipo' => 'WORKFLOW',
                'rota_v1' => 'v1.rmas.transicao.arquivar',
                'rota_v2' => 'v2.rmas.transicao.arquivar',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-016' => [
                'id' => 'CAP-RMA-016',
                'nome' => 'Deletar solicitacao RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'superadministrador',
                'tipo' => 'DELETE/DESATIVAR',
                'rota_v1' => 'v1.rmas.destroy',
                'rota_v2' => 'v2.rmas.destroy',
                'requires_navigation' => false,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'T3-14',
            ],
            'CAP-RMA-017' => [
                'id' => 'CAP-RMA-017',
                'nome' => 'Solucoes de encerramento (15)',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'CONFIG',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-018' => [
                'id' => 'CAP-RMA-018',
                'nome' => 'Controle de Estoque (marcarestoque)',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-019' => [
                'id' => 'CAP-RMA-019',
                'nome' => 'Credito disponivel no RMA',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-020' => [
                'id' => 'CAP-RMA-020',
                'nome' => 'Gestao fiscal (NFs/chaves/emissao)',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'UPDATE',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-021' => [
                'id' => 'CAP-RMA-021',
                'nome' => 'Codigos de rastreio ida/retorno',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'UPDATE',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-022' => [
                'id' => 'CAP-RMA-022',
                'nome' => 'Destinatario / fone / email',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'UPDATE',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-023' => [
                'id' => 'CAP-RMA-023',
                'nome' => 'SN retorno (RN-15)',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'UPDATE',
                'rota_v1' => 'v1.rmas.edit',
                'rota_v2' => 'v2.rmas.edit',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-RMA-024' => [
                'id' => 'CAP-RMA-024',
                'nome' => 'Marcar como (alias orfao)',
                'dominio' => 'rma',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => null,
                'rota_v2' => null,
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido', // Codigo Morto
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'N/A',
            ],

            // Dominio 3: Alertas, Prazos e Prioridades (CAP-ALT-001..005)
            'CAP-ALT-001' => [
                'id' => 'CAP-ALT-001',
                'nome' => 'Alertas de prazo e tempo',
                'dominio' => 'alertas',
                'papel_minimo' => 'operador',
                'tipo' => 'ALERT',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-ALT-002' => [
                'id' => 'CAP-ALT-002',
                'nome' => 'Indicadores Sem NF/SN/Garantia',
                'dominio' => 'alertas',
                'papel_minimo' => 'operador',
                'tipo' => 'ALERT',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-ALT-003' => [
                'id' => 'CAP-ALT-003',
                'nome' => 'Nivel de Prioridade (Baixa/Normal/Alta)',
                'dominio' => 'alertas',
                'papel_minimo' => 'operador',
                'tipo' => 'ALERT',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-ALT-004' => [
                'id' => 'CAP-ALT-004',
                'nome' => 'Urgencia / Threshold R$ 75',
                'dominio' => 'alertas',
                'papel_minimo' => 'operador',
                'tipo' => 'ALERT',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-ALT-005' => [
                'id' => 'CAP-ALT-005',
                'nome' => 'Classificacoes visuais operacionais',
                'dominio' => 'alertas',
                'papel_minimo' => 'operador',
                'tipo' => 'ALERT',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],

            // Dominio 4: Gestao de Creditos (CAP-CRD-001..002)
            'CAP-CRD-001' => [
                'id' => 'CAP-CRD-001',
                'nome' => 'Listagem tabular rica de Creditos',
                'dominio' => 'creditos',
                'papel_minimo' => 'operador',
                'tipo' => 'LIST',
                'rota_v1' => 'rmas.credito.index',
                'rota_v2' => 'rmas.credito.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-03',
            ],
            'CAP-CRD-002' => [
                'id' => 'CAP-CRD-002',
                'nome' => 'Submenus de Creditos (orfao)',
                'dominio' => 'creditos',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => null,
                'rota_v2' => null,
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido', // Codigo Morto
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'N/A',
            ],

            // Dominio 5: Relatorios e Estatisticas (CAP-REL-001..006)
            'CAP-REL-001' => [
                'id' => 'CAP-REL-001',
                'nome' => 'Relatorio RCD (Creditos)',
                'dominio' => 'relatorios',
                'papel_minimo' => 'operador',
                'tipo' => 'REPORT',
                'rota_v1' => 'rmas.relatorios.rcd',
                'rota_v2' => 'rmas.relatorios.rcd',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-05',
            ],
            'CAP-REL-002' => [
                'id' => 'CAP-REL-002',
                'nome' => 'Relatorio RPEC (Estoque)',
                'dominio' => 'relatorios',
                'papel_minimo' => 'operador',
                'tipo' => 'REPORT',
                'rota_v1' => 'rmas.relatorios.rpec',
                'rota_v2' => 'rmas.relatorios.rpec',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-05',
            ],
            'CAP-REL-003' => [
                'id' => 'CAP-REL-003',
                'nome' => 'Relatorio RMPE (Movimentacao)',
                'dominio' => 'relatorios',
                'papel_minimo' => 'operador',
                'tipo' => 'REPORT',
                'rota_v1' => 'rmas.relatorios.rmpe',
                'rota_v2' => 'rmas.relatorios.rmpe',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-05',
            ],
            'CAP-REL-004' => [
                'id' => 'CAP-REL-004',
                'nome' => 'Hub Estatistico de Relatorios',
                'dominio' => 'relatorios',
                'papel_minimo' => 'operador',
                'tipo' => 'REPORT',
                'rota_v1' => 'rmas.relatorios.index',
                'rota_v2' => 'rmas.relatorios.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-05',
            ],
            'CAP-REL-005' => [
                'id' => 'CAP-REL-005',
                'nome' => 'Impressao limpa de relatorios',
                'dominio' => 'relatorios',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => 'rmas.relatorios.rcd',
                'rota_v2' => 'rmas.relatorios.rcd',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-05',
            ],
            'CAP-REL-006' => [
                'id' => 'CAP-REL-006',
                'nome' => 'Informacao adicional persistida',
                'dominio' => 'relatorios',
                'papel_minimo' => 'supervisor',
                'tipo' => 'UPDATE',
                'rota_v1' => 'rmas.relatorios.salvar-informacao-adicional',
                'rota_v2' => 'rmas.relatorios.salvar-informacao-adicional',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-05',
            ],

            // Dominio 6: Cadastros de Parceiros (CAP-PAR-001..007)
            'CAP-PAR-001' => [
                'id' => 'CAP-PAR-001',
                'nome' => 'Gestao de Clientes (CRUD)',
                'dominio' => 'parceiros',
                'papel_minimo' => 'operador',
                'tipo' => 'CREATE',
                'rota_v1' => 'v1.parceiros.clientes.index',
                'rota_v2' => 'v2.parceiros.clientes.index',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-PART-002
                'v3_status' => 'presente',
                'v3_task' => 'T3-02',
            ],
            'CAP-PAR-002' => [
                'id' => 'CAP-PAR-002',
                'nome' => 'Gestao de Fornecedores (CRUD)',
                'dominio' => 'parceiros',
                'papel_minimo' => 'operador',
                'tipo' => 'CREATE',
                'rota_v1' => 'v1.parceiros.fornecedores.index',
                'rota_v2' => 'v2.parceiros.fornecedores.index',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-PART-003
                'v3_status' => 'presente',
                'v3_task' => 'T3-02',
            ],
            'CAP-PAR-003' => [
                'id' => 'CAP-PAR-003',
                'nome' => 'Gestao de Fabricantes (CRUD)',
                'dominio' => 'parceiros',
                'papel_minimo' => 'operador',
                'tipo' => 'CREATE',
                'rota_v1' => 'v1.parceiros.fabricantes.index',
                'rota_v2' => 'v2.parceiros.fabricantes.index',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-PART-004
                'v3_status' => 'presente',
                'v3_task' => 'T3-02',
            ],
            'CAP-PAR-004' => [
                'id' => 'CAP-PAR-004',
                'nome' => 'Gestao de Assistencias (CRUD)',
                'dominio' => 'parceiros',
                'papel_minimo' => 'operador',
                'tipo' => 'CREATE',
                'rota_v1' => 'v1.parceiros.assistencias-tecnicas.index',
                'rota_v2' => 'v2.parceiros.assistencias-tecnicas.index',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-PART-005
                'v3_status' => 'presente',
                'v3_task' => 'T3-02',
            ],
            'CAP-PAR-005' => [
                'id' => 'CAP-PAR-005',
                'nome' => 'RG / IE nos parceiros',
                'dominio' => 'parceiros',
                'papel_minimo' => 'operador',
                'tipo' => 'UPDATE',
                'rota_v1' => 'v1.parceiros.clientes.index',
                'rota_v2' => 'v2.parceiros.clientes.index',
                'requires_navigation' => true,
                'requires_persistence' => true,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-PART-DATA-001
                'v3_status' => 'presente',
                'v3_task' => 'T3-02',
            ],
            'CAP-PAR-006' => [
                'id' => 'CAP-PAR-006',
                'nome' => 'RMAs associados ao parceiro',
                'dominio' => 'parceiros',
                'papel_minimo' => 'operador',
                'tipo' => 'DETAIL',
                'rota_v1' => 'v1.parceiros.clientes.index',
                'rota_v2' => 'v2.parceiros.clientes.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'revisado', // PAR15-PART-001/006
                'v3_status' => 'planejado',
                'v3_task' => 'T3-14',
            ],
            'CAP-PAR-007' => [
                'id' => 'CAP-PAR-007',
                'nome' => 'Modelo assistencias(tipo)',
                'dominio' => 'parceiros',
                'papel_minimo' => 'operador',
                'tipo' => 'BACKGROUND/DOMAIN',
                'rota_v1' => null,
                'rota_v2' => null,
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido', // Codigo Morto
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'N/A',
            ],

            // Dominio 7: Controle e Auditoria (CAP-AUD-001..004)
            'CAP-AUD-001' => [
                'id' => 'CAP-AUD-001',
                'nome' => 'Hub de Controle Operacional',
                'dominio' => 'auditoria',
                'papel_minimo' => 'supervisor',
                'tipo' => 'PAGE',
                'rota_v1' => 'rmas.controle.index',
                'rota_v2' => 'v2.identidade.controle.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'T3-14',
            ],
            'CAP-AUD-002' => [
                'id' => 'CAP-AUD-002',
                'nome' => 'Logs de Autenticacao (acesso)',
                'dominio' => 'auditoria',
                'papel_minimo' => 'supervisor',
                'tipo' => 'AUDIT',
                'rota_v1' => 'rmas.controle.index',
                'rota_v2' => 'v2.identidade.controle.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
            'CAP-AUD-003' => [
                'id' => 'CAP-AUD-003',
                'nome' => 'Logs de Modificacao de RMA',
                'dominio' => 'auditoria',
                'papel_minimo' => 'supervisor',
                'tipo' => 'AUDIT',
                'rota_v1' => 'rmas.controle.index',
                'rota_v2' => 'v2.identidade.controle.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-04',
            ],
            'CAP-AUD-004' => [
                'id' => 'CAP-AUD-004',
                'nome' => 'Acao Ver / Detalhe do log',
                'dominio' => 'auditoria',
                'papel_minimo' => 'supervisor',
                'tipo' => 'DETAIL',
                'rota_v1' => 'rmas.controle.index',
                'rota_v2' => 'v2.identidade.controle.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-04',
            ],

            // Dominio 8: Logistica (CAP-LOG-001..002)
            'CAP-LOG-001' => [
                'id' => 'CAP-LOG-001',
                'nome' => 'Transporte para Porto Alegre',
                'dominio' => 'logistica',
                'papel_minimo' => 'operador',
                'tipo' => 'PAGE',
                'rota_v1' => 'v1.rmas.logistica.frete-porto-alegre',
                'rota_v2' => 'v2.rmas.logistica.frete-porto-alegre',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'T3-14',
            ],
            'CAP-LOG-002' => [
                'id' => 'CAP-LOG-002',
                'nome' => 'Destinatarios com frete e CFOP',
                'dominio' => 'logistica',
                'papel_minimo' => 'operador',
                'tipo' => 'DETAIL',
                'rota_v1' => 'v1.parceiros.clientes.index',
                'rota_v2' => 'v2.parceiros.clientes.index',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'T3-14',
            ],

            // Dominio 9: Outros e Auxiliares (CAP-AUX-001..004)
            'CAP-AUX-001' => [
                'id' => 'CAP-AUX-001',
                'nome' => 'Ajuda / Procedimento de RMA',
                'dominio' => 'auxiliares',
                'papel_minimo' => 'operador',
                'tipo' => 'PAGE',
                'rota_v1' => 'v1.rmas.ajuda',
                'rota_v2' => 'v2.rmas.ajuda',
                'requires_navigation' => true,
                'requires_persistence' => false,
                'requires_browser' => true,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'T3-14',
            ],
            'CAP-AUX-002' => [
                'id' => 'CAP-AUX-002',
                'nome' => 'Avisar alguem (stub)',
                'dominio' => 'auxiliares',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => null,
                'rota_v2' => null,
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido', // Codigo Morto
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'N/A',
            ],
            'CAP-AUX-003' => [
                'id' => 'CAP-AUX-003',
                'nome' => 'Enviar e-mail (stub)',
                'dominio' => 'auxiliares',
                'papel_minimo' => 'operador',
                'tipo' => 'ACTION',
                'rota_v1' => null,
                'rota_v2' => null,
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido', // Codigo Morto
                'status_apresentacao' => 'concluido',
                'v3_status' => 'planejado',
                'v3_task' => 'N/A',
            ],
            'CAP-AUX-004' => [
                'id' => 'CAP-AUX-004',
                'nome' => 'Paginas de Erro 403 / 404',
                'dominio' => 'auxiliares',
                'papel_minimo' => 'visitante',
                'tipo' => 'PAGE',
                'rota_v1' => 'v1.rmas.index',
                'rota_v2' => 'v2.rmas.index',
                'requires_navigation' => false,
                'requires_persistence' => false,
                'requires_browser' => false,
                'status_funcional' => 'concluido',
                'status_apresentacao' => 'concluido',
                'v3_status' => 'presente',
                'v3_task' => 'T3-01',
            ],
        ];
    }

    /**
     * Retorna capacidades ativas (excluindo código morto deliberado).
     */
    public static function ativas(): array
    {
        return array_filter(self::all(), function ($cap) {
            return ! in_array($cap['id'], [
                'CAP-ID-011',
                'CAP-RMA-009',
                'CAP-RMA-024',
                'CAP-CRD-002',
                'CAP-PAR-007',
                'CAP-AUX-002',
                'CAP-AUX-003',
            ]);
        });
    }

    /**
     * Retorna capacidades que exigem rota e navegação ativa na interface.
     */
    public static function descobríveis(): array
    {
        return array_filter(self::ativas(), function ($cap) {
            return $cap['requires_navigation'] === true && $cap['rota_v1'] !== null && $cap['rota_v2'] !== null;
        });
    }
}
